<template>
    <div class="card-group">
        <router-link to="/create-room">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">Create a room</p>
                </div>
            </div>
        </router-link>
        <router-link to="/join-room">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">Join a room</p>
                </div>
            </div>
        </router-link>
    </div>
</template>